deviers: block: remove unused LOOP_SET_BLOCK_SIZE
drivers/block/loop.c:1484:7: error: 'LOOP_SET_BLOCK_SIZE' undeclared (first use in this function)
  case LOOP_SET_BLOCK_SIZE:
       ^